### ISSUE TITLE
Links in grimoires are broken

### ISSUE THREAD

**Issue by neverfox** [jafingerhut/jafingerhut.github.com#5]
If you click on any of the links on your grimoires, you get an unknown page. This is because the path is missing a piece. `http://conj.io/store/v0/org.clojure/clojure/1.7.0-alpha4/clojure.core/...` should be `http://conj.io/store/v0/org.clojure/clojure/1.7.0-alpha4/clj/clojure.core/...`.

**Comment by jafingerhut** [comment]
Thanks for the notice.  Should be fixed now.  Let me know if you find any other broken links.
